# Configuration file for scenario theta

# swmm inp file
swmm_input: delta
# state definitions
states:
      - !!python/tuple
        - "basin_N1"
        - depthN
      - !!python/tuple
        - "basin_N2"
        - depthN
      - !!python/tuple
        - "basin_N3"
        - depthN
      - !!python/tuple
        - "basin_N4"
        - depthN
      - !!python/tuple
        - "basin_C"
        - depthN
      - !!python/tuple
        - "basin_S"
        - depthN
      - !!python/tuple
        - "orifice_N"
        - flow
      - !!python/tuple
        - "orifice_N32"
        - flow
      - !!python/tuple
        - "orifice_N21"
        - flow
      - !!python/tuple
        - "orifice_E"
        - flow
      - !!python/tuple
        - "conduit_N43"
        - flow
      - !!python/tuple
        - "conduit_Eup"
        - flow
      - !!python/tuple
        - "conduit_Ndown"
        - flow
      - !!python/tuple
        - "conduit_NupB"
        - flow
      - !!python/tuple
        - "conduit_NupA"
        - flow
      - !!python/tuple
        - "conduit_N32up"
        - flow
      - !!python/tuple
        - "conduit_N32down"
        - flow
      - !!python/tuple
        - "conduit_N21up"
        - flow
      - !!python/tuple
        - "conduit_N21down"
        - flow
      - !!python/tuple
        - "conduit_Sup"
        - flow
      - !!python/tuple
        - "conduit_Edown"
        - flow
      - !!python/tuple
        - "conduit_Sdown"
        - flow
      - !!python/tuple
        - "conduit_Ssc"
        - flow
      - !!python/tuple
        - "conduit_N2sc"
        - flow
      - !!python/tuple
        - "conduit_N3sc"
        - flow
      - !!python/tuple
        - "conduit_N4sc"
        - flow
      - !!python/tuple
        - "conduit_EinflowA"
        - flow
      - !!python/tuple
        - "conduit_Eout"
        - flow
      - !!python/tuple
        - "conduit_EinflowB"
        - flow
      - !!python/tuple
        - "conduit_Csc"
        - flow
      - !!python/tuple
        - "conduit_N1sc"
        - flow

# Action space
action_space:
        - "weir_N32"
        - "weir_N21"
        - "weir_N"
        - "weir_E"
        - "orifice_S"

# Performance Targets
performance_targets:
        - !!python/tuple
          - "basin_N1"
          - depthN
        - !!python/tuple
          - "basin_N2"
          - depthN
        - !!python/tuple
          - "basin_N3"
          - depthN
        - !!python/tuple
          - "basin_N4"
          - depthN
        - !!python/tuple
          - "basin_C"
          - depthN
        - !!python/tuple
          - "basin_S"
          - depthN
        - !!python/tuple
          - "junc_Ssc"
          - flooding
        - !!python/tuple
          - "junc_Csc"
          - flooding
        - !!python/tuple
          - "junc_N1sc"
          - flooding
        - !!python/tuple
          - "junc_N2sc"
          - flooding
        - !!python/tuple
          - "junc_N3sc"
          - flooding
        - !!python/tuple
          - "junc_N4sc"
          - flooding
        - !!python/tuple
          - "junc_EinflowA"
          - flooding
        - !!python/tuple
          - "junc_Eout"
          - flooding
        - !!python/tuple
          - "orifice_N"
          - flow
        - !!python/tuple
          - "orifice_N32"
          - flow
        - !!python/tuple
          - "orifice_N21"
          - flow
        - !!python/tuple
          - "orifice_E"
          - flow
        - !!python/tuple
          - "conduit_Eout"
          - flow
